server:
  port: 9190
spring:
  jpa:
    properties:
      hibernate:
        type: trace
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql : true
    show_sql: true
  h2:
    console:
      enabled: true
  profiles.include: oauth
  output:
    ansi:
      enabled : always
  session:
    store-type: jdbc

# Test OAuth

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: test
#            client-secret: test
#            scope: profile, email



#  datasource:
#    hikari:
#      driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy

#log4jdbc:
#  spylogdelegator:
#    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

#logging:
#  level:
#    org.hibernate.SQL : DEBUG
#    org.hibernate.type : TRACE
