server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        type: trace
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql : true
    show_sql: true
  profiles.include: oauth,real-db
  output:
    ansi:
      enabled : always
  session:
    store-type: jdbc
