spring:
  profiles.inlcude: oauth,real-db
  jpa:
    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type : jdbc
  output:
    ansi:
      enabled: always